_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
# set `[n]` to use nth GPU
gpus: [0]

min_epochs: 100
max_epochs: ${datamodule._max_epochs}

progress_bar_refresh_rate: 1
num_sanity_val_steps: 0

benchmark: False
deterministic: True
