# output paths for hydra logs
run:
  dir: "../logs/${experiment_name}/${now:%Y-%m-%d-%H-%M-%S}"
sweep:
  # Not works if we put ${project_dir}. Why? I do not know...
  dir: "../logs_multi/${experiment_name}/${now:%Y-%m-%d-%H-%M-%S}"
  subdir: ${hydra.job.num}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
job:
  env_set:
    EXAMPLE_VAR: "example_value"
