defaults:
  - override /hydra/sweeper/sampler: random
  - override /hydra/sweeper: optuna

hydra:
  # here we define Optuna hyperparameter search
  # it optimizes for value returned from function with @hydra.main decorator
  # learn more here: https://hydra.cc/docs/next/plugins/optuna_sweeper
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: "sqlite:///../hparams.db"
    study_name: null
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: null

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.RandomSampler