_target_: model.StaticGraphModel

defaults:
  - common_model.yaml

use_projector: False
lambda_proj: null
projected_channels: null
projector_infonce_temperature: null
projector_readout_types: null

use_predictor: True
lambda_pred: 1.0
predictor_type: ${datamodule._predictor_type}
metrics: ${datamodule._metrics}

learning_rate: 0.01
weight_decay: 0.0000049316
dropout_channels: 0.15

subname: baseline
