model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "./checkpoints/"  # parent path is hydra.dir
  filename: "epoch_{epoch:03d}"
  monitor: # Lazy loading, name of the logged metric which determines when model is improving
  mode: "max" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: False
  verbose: True
  auto_insert_metric_name: True
