_target_: data.DyGraphDataModule

# JODIEDataset/reddit, JODIEDataset/wikipedia, JODIEDataset/mooc, JODIEDataset/lastfm
# ogbn-arxiv, ogbl-collab, ogbl-citation2
# SingletonICEWS18, SingletonGDELT
# BitcoinOTC
dataset_name: ogbl-collab
dataset_path: ${dataset_path} # dataset_path is specified in config.yaml

# SnapshotGraphLoader, TemporalDataLoader, EdgeLoader, NoLoader
dataloader_type: SnapshotGraphLoader
eval_dataloader_type: NoLoader

batch_size: 8
eval_batch_size: # None

step_size: 1
use_temporal_data: False
use_sparse_tensor: False

verbose: 2
num_workers: 0
