_target_: data.DyGraphDataModule

# JODIEDataset/reddit, JODIEDataset/wikipedia, JODIEDataset/mooc, JODIEDataset/lastfm
# ogbn-arxiv, ogbl-collab, ogbl-citation2
# SingletonICEWS18, SingletonGDELT
# BitcoinOTC
dataset_name: ogbl-collab
dataset_path: ${dataset_path} # dataset_path is specified in config.yaml

# SnapshotGraphLoader, TemporalDataLoader, EdgeLoader, NoLoader
dataloader_type: SnapshotGraphLoader
eval_dataloader_type: NoLoader

batch_size: 8
eval_batch_size: # None

step_size: 1
use_temporal_data: False
use_sparse_tensor: True

verbose: 2
num_workers: 0

# Will be inherited to the model
_predictor_type: Edge/HadamardProduct
_metrics: ["hits@10", "hits@50", "hits@100"]

# Will be inherited to the trainer
_max_epochs: 700
